import svg4everybody from 'svg4everybody';
import objectFitImages from 'object-fit-images';
import anchor from '../blocks/js-functions/anchor';
import { freezebuttons } from '../blocks/js-functions/freeze';
import scrollanimation from '../blocks/js-functions/scrollanimation';
import popups from '../blocks/popups/popups';
import scrollbar from '../blocks/scrollbar/scrollbar';
import slider from '../blocks/slider/slider';
import tooltips from '../blocks/tooltip/tooltip';
import tabs from '../blocks/tabs/tabs';
import maps from '../blocks/map/map';
import '../blocks/accordion/accordion';
import '../blocks/dropdown/dropdown';
import { headerResize, openMenu } from '../components/header/header';
// import showMore from '../blocks/person/person';
import ffDetect from '../blocks/text-block/text-block';
import switchText from '../blocks/text-switcher/text-switcher';
import moveStatistic from '../components/patients/patients';
import floatBlocks from '../blocks/js-functions/floatblocks';
import showPartners from '../blocks/partners/partners';
import childDescribeResize from '../blocks/child/child';

const $ = window.$;

$(() => {
  svg4everybody();
  objectFitImages();
  anchor();
  freezebuttons();
  popups();
  scrollbar();
  slider();
  tooltips();
  tabs();
  maps();
  scrollanimation();
  headerResize();
  // showMore();
  openMenu();
  ffDetect();
  switchText();
  moveStatistic();
  floatBlocks();
  showPartners();
  childDescribeResize();
});
